name: documentation
on:
    push:
        paths: ['examples/**', 'packages/**']
permissions:
    contents: write
jobs:
    documentation:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.2
              with:
                  persist-credentials: false
            - name: Install
              run: |
                  npm install
                  npm run bootstrap
            - name: Build library
              run: |
                  cd packages/core
                  npm run build
                  cd ../../
                  npm run build
            - name: Build storybook
              run: |
                  npm run build-storybook
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4.4.0
              with:
                  branch: gh-pages
                  folder: storybook-static
                  clean: true
