name: tests
on:
    push:
        paths: ['packages/**']
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.2
              with:
                  persist-credentials: false
            - name: Install
              run: |
                  npm install
                  npm run bootstrap
            - name: Build library
                run: |
                  npm run build
            - name: Style check
              run: |
                  npm run prettier-check
            - name: Lint check
              run: |
                  npm run lint
                  npm run lint-examples
            - name: Tests
              run: |
                  npm run test
